name: Docker Build and Push
on: [push, pull_request]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-20.04
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: docker/setup-buildx-action@v1
      # -
      #   uses: docker/login-action@v1
      #   with:
      #     username: auserid
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        uses: oprypin/find-latest-tag@v1
        with:
          repository: dysnix/github-actions-runner
          prefix: v
        id: latest
      -
        id: env
        run: |
          latest=${{ steps.latest.outputs.tag }}; latest=${latest#v}
          echo "::set-output name=runnerVersion::${latest}"

      # When building we always use the latest runner version available
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: matter-labs/github-actions-runner
          build-args: |
            RUNNER_VERSION=${{ steps.env.outputs.runnerVersion }}
